services:
    _defaults:
        public: true

    coreshop.pimcore.document.tag.country:
        class: CoreShop\Component\Resource\Pimcore\ResourceDocumentTagFactory
        arguments:
            - 'CoreShop\Bundle\ResourceBundle\CoreExtension\Document\Select'
            - 'coreshop.repository.country'
            - 'name'
        tags:
            - { name: coreshop.pimcore.document.tag, type: coreshop_country }

    coreshop.pimcore.document.tag.state:
        class: CoreShop\Component\Resource\Pimcore\ResourceDocumentTagFactory
        arguments:
            - 'CoreShop\Bundle\ResourceBundle\CoreExtension\Document\Select'
            - 'coreshop.repository.state'
            - 'name'
        tags:
            - { name: coreshop.pimcore.document.tag, type: coreshop_state }

    coreshop.pimcore.document.tag.zone:
        class: CoreShop\Component\Resource\Pimcore\ResourceDocumentTagFactory
        arguments:
            - 'CoreShop\Bundle\ResourceBundle\CoreExtension\Document\Select'
            - 'coreshop.repository.zone'
            - 'name'
        tags:
            - { name: coreshop.pimcore.document.tag, type: coreshop_zone }