services:
    _defaults:
        public: true

    CoreShop\Bundle\AddressBundle\Collector\CountryCollector:
        arguments:
            - '@coreshop.context.country'
            - false
        tags:
            - { name: data_collector, template: 'CoreShopAddressBundle:Collector:country.html.twig', id: coreshop.country_collector }
