services:
    _defaults:
        public: true

    CoreShop\Bundle\AddressBundle\Collector\CountryCollector:
        arguments:
            - '@CoreShop\Component\Address\Context\CountryContextInterface'
            - '@Pimcore\Http\Request\Resolver\PimcoreContextResolver'
            - false
        tags:
            - { name: data_collector, template: '@CoreShopAddress/Collector/country.html.twig', id: coreshop.country_collector }
